# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Habitacion 1', 'Habitacion 1'), ('Habitacion 2', 'Habitacion 2'), ('Habitacion 3', 'Habitacion 3'), ('Habitacion 4', 'Habitacion 4'), ('Habitacion 5', 'Habitacion 5'), ('Habitacion 6', 'Habitacion 6'), ('Habitacion 7', 'Habitacion 7'), ('Habitacion 8', 'Habitacion 8')], max_length=103)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('SI', 'SIMPLE'), ('DO', 'DOBLE')], default='SI', max_length=2)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('consulta', models.CharField(max_length=1000)),
                ('fecha', models.CharField(max_length=20)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SI', 'SIMPLE'), ('DO', 'DOBLE')], default='SI', max_length=2)),
                ('numero', models.CharField(choices=[('UN', '1'), ('DO', '2'), ('TR', '3'), ('CU', '4'), ('CI', '5'), ('SE', '6'), ('SI', '7'), ('OC', '8')], default='UN', max_length=2)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=8)),
                ('salida', models.CharField(max_length=30)),
                ('ingreso', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=50)),
                ('cancelar', models.CharField(max_length=20)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
                ('detalle', models.ManyToManyField(to='Aplicacion1.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=25)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=10)),
                ('piezas', models.CharField(max_length=500)),
                ('entrega', models.CharField(max_length=50)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
